name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build
      run: |
        cd website
        npm install
        npm run build
        touch ./build/cryptography-openssl-kernel-crypto/.nojekyll
        ls -al ./build/cryptography-openssl-kernel-crypto/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./website/build/cryptography-openssl-kernel-crypto/
